import * as db from './db.js';
import {newProject,uid,today,money,totals,round,validNumber,validDate,validateReceipt} from './model.js';
import {renderInvoice,presets,sanitizeTemplate,checkTemplate,escapeHTML as e} from './invoice.js';
import {compressImage,parseReceiptImage} from './receipt.js';
const $=s=>document.querySelector(s);
let state,projects=[],templates=[],images=new Map(),tab='project',saveChain=Promise.resolve(),revision=0,scanBusy=false,renderBusy=false;
function message(text){$('#message').textContent=text;$('#message').hidden=!text;}
function fail(error){message(error.message||String(error));}
function setting(key){try{return localStorage.getItem(`wrapsheet.${key}`)||'';}catch{return '';}}
function setSetting(key,value){try{if(value)localStorage.setItem(`wrapsheet.${key}`,value);else localStorage.removeItem(`wrapsheet.${key}`);}catch{message('Browser settings could not be saved. Your project remains in IndexedDB.');}}
function setPath(path,value){const parts=path.split('.');let obj=state;for(const p of parts.slice(0,-1))obj=obj[p];obj[parts.at(-1)]=value;}
function getPath(path){return path.split('.').reduce((o,k)=>o[k],state);}
function save(){
  const snapshot=structuredClone(state),rev=++revision;snapshot.updatedAt=Date.now();$('#save-status').textContent='Saving…';
  saveChain=saveChain.catch(()=>{}).then(()=>db.put('projects',snapshot)).then(()=>{if(rev===revision)$('#save-status').textContent='✓ Saved on this device';const i=projects.findIndex(p=>p.id===snapshot.id);if(i<0)projects.push(snapshot);else projects[i]=snapshot;updatePicker();}).catch(error=>{$('#save-status').textContent='Not saved — retry';message(`Could not save your project: ${error.message}. Free device storage and use Retry save. Keep this tab open.`);throw error;});
  saveChain.catch(()=>{});return saveChain;
}
function updatePicker(){const picker=$('#project-picker');picker.innerHTML=projects.map(p=>`<option value="${p.id}">${e(p.project.projectTitle||'Untitled production')}</option>`).join('');picker.value=state.id;}
function summary(){const t=totals(state),c=state.project.currency;$('#summary-name').textContent=state.project.projectTitle||'Untitled production';$('#labor-total').textContent=money(t.labor,c);$('#tax-total').textContent=money(t.tax,c);$('#tax-percent').textContent=`(${state.project.taxRate}%)`;$('#expense-total').textContent=money(t.expenses,c);$('#grand-total').textContent=money(t.total,c);const pending=state.expenses.filter(r=>!r.verified).length;$('#receipt-status').textContent=pending?`${pending} receipt${pending===1?'':'s'} awaiting review · excluded from total`:`${state.expenses.length} verified expense${state.expenses.length===1?'':'s'} · ready to wrap`;}
function field(label,path,type='text',extra=''){return `<label>${label}<input data-field="${path}" type="${type}" value="${e(getPath(path))}" ${extra}></label>`;}
function area(label,path){return `<label class="full">${label}<textarea data-field="${path}">${e(getPath(path))}</textarea></label>`;}
function select(label,path,options){return `<label>${label}<select data-field="${path}">${options.map(o=>{const [value,title]=Array.isArray(o)?o:[o,o];return `<option value="${e(value)}" ${getPath(path)===value?'selected':''}>${e(title)}</option>`;}).join('')}</select></label>`;}
function check(label,path){return `<label class="check"><input type="checkbox" data-field="${path}" ${getPath(path)?'checked':''}>${label}</label>`;}
function panel(title,description,content,tag=''){return `<div class="panel"><div class="section-head"><div><h2>${title}</h2><p>${description}</p></div>${tag?`<span class="tag">${tag}</span>`:''}</div>${content}</div>`;}
function projectView(){return panel('Set the scene.','A few details now. A polished invoice at wrap.',`<div class="form-grid">${field('Project title','project.projectTitle','text','placeholder="e.g. Autumn campaign — Seoul" maxlength="200"')}${field('Client / production company','project.clientName','text','placeholder="Who are we making this for?" maxlength="200"')}${select('Currency','project.currency',[['KRW','KRW — Korean won'],['USD','USD — US dollar'],['EUR','EUR — Euro']])}${field('Invoice number','project.invoiceNumber')}${field('Shoot start','project.shootStart','date')}${field('Shoot end','project.shootEnd','date')}${field('Invoice date','project.invoiceDate','date')}${field('Payment due','project.dueDate','date')}${area('Client address','project.clientAddress')}</div><p class="hint">Changing currency changes the unit only; it does not convert existing amounts.</p><div class="actions"><button class="primary" data-go="work">Continue to work →</button><button data-action="retry-save">Retry save</button><button data-action="backup">Download project backup</button></div>`,'PRODUCTION DETAILS')+panel('The name behind the frame.','Your contractor details travel with this project.',`<div class="form-grid">${field('Contractor / company','contractor.name','text','placeholder="Your name or studio"')}${field('Email','contractor.email','email')}${field('Phone','contractor.phone','tel')}${field('Tax / business registration number','contractor.taxId')}${area('Address','contractor.address')}${field('Bank name','contractor.bankName')}${field('Account number / payment reference','contractor.accountNumber')}${area('Payment terms','contractor.paymentTerms')}</div>`);}
const laborTypes=['Shoot Day','Prep Day','Travel Day','Half Day','Overtime','Kit Rental','Equipment Rental','Mileage','Per Diem','Assistant','Post-production','Other'];
function workView(){return panel('Every hour. Every piece of kit.','Build your agreed work items. Quantities can be fractional.',`<div class="inline"><label style="flex:1">Add a work item<select id="labor-kind">${laborTypes.map(t=>`<option>${t}</option>`).join('')}</select></label><button class="primary" data-action="add-labor" style="align-self:end">＋ Add item</button></div>${state.labor.length?state.labor.map((r,i)=>`<div class="row-card"><div class="row-top"><strong>${String(i+1).padStart(2,'0')} / <span data-row-total="${i}">${money(round(r.rate*r.quantity,state.project.currency),state.project.currency)}</span></strong><button class="remove" data-action="remove-labor" data-id="${r.id}">Remove</button></div><div class="form-grid">${field('Description',`labor.${i}.description`)}${field('Work date',`labor.${i}.date`,'date')}${select('Unit',`labor.${i}.unit`,['day','hour','item','km','mile'])}${field('Quantity',`labor.${i}.quantity`,'number','min="0" max="1000000" step="0.01"')}${field(`Rate (${state.project.currency})`,`labor.${i}.rate`,'number','min="0" max="1000000000000" step="any"')}${check('Taxable',`labor.${i}.taxable`)}</div></div>`).join(''):'<div class="empty">No work logged yet. Add your first shoot day above.</div>'}<div class="form-grid">${field('Tax on taxable work (%)','project.taxRate','number','min="0" max="100" step="0.01"')}</div><p class="hint">Default is 0%. Set the rate agreed for this invoice. Expenses are pass-through reimbursements, with no additional tax applied.</p><div class="actions"><button class="primary" data-go="receipts">Continue to receipts →</button></div>`,'WORK LOG');}
function receiptView(){return panel('Proof, without the paperwork.','Capture it now. Check the details. Get back to the set.',`<div class="upload-box"><span class="upload-icon">▤ ＋</span><h3>Drop the admin. Keep the receipt.</h3><p>Korean or English. Camera photo or image file.</p><div class="actions"><label class="file-button">◉ Take a photo<input id="camera-input" type="file" accept="image/*" capture="environment"></label><label class="file-button">↥ Upload image<input id="receipt-input" type="file" accept="image/*" multiple></label><button data-action="manual-receipt">Add manually</button></div><p class="hint">Photos stay on this device until you choose to scan with Gemini.</p></div><div class="actions"><span class="hint">${state.expenses.length} expenses · only verified items enter your invoice</span></div>${state.expenses.map((r,i)=>`<div class="row-card"><div class="row-top"><span class="badge ${r.verified?'verified':''}">${r.verified?'✓ VERIFIED':'○ NEEDS REVIEW'} · ${String(i+1).padStart(2,'0')}</span><button class="remove" data-action="remove-receipt" data-id="${r.id}">Remove</button></div><div class="receipt-card"><div>${images.get(r.receiptId)?`<a href="${e(images.get(r.receiptId).imageFull)}" target="_blank" rel="noopener" aria-label="Open receipt photo"><img class="receipt-image" src="${e(images.get(r.receiptId).imageThumbnail)}" alt="Receipt photo for ${e(r.vendor||'review')}"></a>`:'<div class="empty">Manual<br>expense</div>'}</div><div><div class="form-grid">${field('Vendor / 거래처',`expenses.${i}.vendor`)}${field('Date / 날짜',`expenses.${i}.date`,'date')}${field('Total paid / 합계',`expenses.${i}.total`,'number','min="0" step="any"')}${field('Included VAT / 부가세',`expenses.${i}.vat`,'number','min="0" step="any"')}${field('Category / expense note',`expenses.${i}.category`)}${select('Receipt currency',`expenses.${i}.currency`,[['','Unknown — choose'],['KRW','KRW'],['USD','USD'],['EUR','EUR']])}</div>${r.warning?`<p class="notice">${e(r.warning)}</p>`:''}<div class="actions">${!r.verified?`<button class="primary" data-action="confirm-receipt" data-id="${r.id}">Confirm expense</button>`:'<span class="hint">Editing marks this receipt for re-verification.</span>'}${r.receiptId?`<button data-action="scan" data-id="${r.id}" ${scanBusy?'disabled':''}>${scanBusy?'Scanning…':'Scan with Gemini'}</button>`:''}</div></div></div></div>`).join('')}<div class="actions"><button class="primary" data-go="invoice">Review invoice →</button></div>`);}
function invoiceView(){return panel('Your name. Your invoice.','Edit highlighted text directly in the preview. Amount changes update your saved work and totals.',`<div class="invoice-controls">${select('Invoice template','invoice.templateId',[...presets.map(p=>[p.id,p.name]),...templates.map(t=>[t.id,t.name])])}${field('Accent color','invoice.accent','color')}<div><label class="file-button">Upload logo<input type="file" id="logo-input" accept="image/*"></label>${state.contractor.logo?'<button data-action="remove-logo">Remove logo</button>':''}</div><div><label class="file-button">Upload HTML template<input type="file" id="template-input" accept=".html,text/html"></label></div><details><summary>Labels & sections</summary><div class="form-grid">${Object.keys(state.invoice.labels).map(k=>field(k.replace(/([A-Z])/g,' $1'),`invoice.labels.${k}`)).join('')}${check('Payment information','invoice.options.showBankInfo')}${check('Included receipt VAT','invoice.options.showVat')}${check('Receipt proof gallery','invoice.options.showReceiptGallery')}${check('Expense categories','invoice.options.showExpenseCategories')}${check('Notes','invoice.options.showNotes')}${check('Bilingual headings (EN / KR)','invoice.options.bilingualLabels')}</div></details><details><summary>Invoice details & notes</summary><div class="form-grid">${field('Invoice number','project.invoiceNumber')}${field('Invoice date','project.invoiceDate','date')}${field('Payment due','project.dueDate','date')}${field('Client name','project.clientName')}${area('Notes','project.notes')}${area('Payment terms','contractor.paymentTerms')}${area('Footer','contractor.footer')}</div></details></div><p class="hint">HTML uploads support placeholders and safe structural HTML. Scripts, styles and external assets are removed. <a href="./example-template.html" download style="color:var(--accent)">Download starter template ↗</a></p><div class="actions"><button class="primary" data-action="export">↓ Export PDF</button><button data-go="work">Edit work</button><button data-go="receipts">Edit receipts</button></div><p id="export-status" role="status" class="hint"></p>`)+`<div class="preview-wrap"><div id="invoice-preview" class="invoice-paper"></div></div>`;}
function enrichedState(){return {...state,expenses:state.expenses.map(r=>({...r,imageThumbnail:images.get(r.receiptId)?.imageThumbnail||''}))};}
function template(){return templates.find(t=>t.id===state.invoice.templateId)||presets.find(t=>t.id===state.invoice.templateId)||presets[0];}
function preview(){if(!$('#invoice-preview'))return;$('#invoice-preview').style.setProperty('--invoice-accent',state.invoice.accent);$('#invoice-preview').innerHTML=renderInvoice(template(),enrichedState(),{editable:true});}
function render(){if(!state)return;$('#view').innerHTML=tab==='project'?projectView():tab==='work'?workView():tab==='receipts'?receiptView():invoiceView();document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'step':'false');});summary();preview();}
async function go(next){if(scanBusy||renderBusy){message('Please wait for the current operation to finish.');return;}await saveChain;tab=next;location.hash=next;message('');render();}
function updateField(path,value,element){
  const old=getPath(path);if(typeof old==='number'||element.type==='number'||element.dataset.type==='number'){
    const max=path==='project.taxRate'?100:path.endsWith('.quantity')?1e6:1e12;if(!validNumber(value,max))throw new Error(`Enter a valid non-negative number${path==='project.taxRate'?' between 0 and 100':''}.`);value=Number(value);
    if(path.endsWith('.rate')||/^expenses\.\d+\.(total|vat)$/.test(path))value=round(value,state.project.currency);
  }
  if((path.endsWith('.date')||/project\.(invoiceDate|dueDate|shootStart|shootEnd)/.test(path))&&value&&!validDate(value))throw new Error('Use a valid date in YYYY-MM-DD format.');
  if(path==='invoice.accent'&&!/^#[0-9a-f]{6}$/i.test(value))throw new Error('Choose a valid accent color.');
  setPath(path,value);
  if(path.startsWith('expenses.')){
    const r=state.expenses[Number(path.split('.')[1])];r.verified=false;
    const card=element.closest('.row-card');
    if(card){const badge=card.querySelector('.badge');badge.classList.remove('verified');badge.textContent='○ NEEDS REVIEW';
      if(!card.querySelector('[data-action=confirm-receipt]')){const actions=card.querySelector('.actions');const button=document.createElement('button');button.className='primary';button.dataset.action='confirm-receipt';button.dataset.id=r.id;button.textContent='Confirm expense';actions.prepend(button);}}
  }
  save();summary();
  if(path.startsWith('labor.')){const i=Number(path.split('.')[1]),r=state.labor[i],el=document.querySelector(`[data-row-total="${i}"]`);if(el)el.textContent=money(round(r.rate*r.quantity,state.project.currency),state.project.currency);}
}
async function loadProject(id){const loaded=await db.get('projects',id);if(!loaded)throw new Error('Project could not be found.');state=loaded;images=new Map();for(const r of state.expenses){if(r.receiptId){const image=await db.get('receipts',r.receiptId);if(image)images.set(r.receiptId,image);}}setSetting('currentProjectId',id);updatePicker();render();}
async function addPhoto(file){const full=await compressImage(file),thumb=await compressImage(file,500,.78);const record={id:uid(),projectId:state.id,imageFull:full,imageThumbnail:thumb,name:file.name};await db.put('receipts',record);images.set(record.id,record);state.expenses.push({id:uid(),receiptId:record.id,vendor:'',date:'',total:'',vat:'',currency:state.project.currency,category:'',verified:false,warning:'Review the photo or scan it with Gemini.'});await save();}
async function scan(id){const r=state.expenses.find(r=>r.id===id);if(!r)return;if(!navigator.onLine)throw new Error('You are offline. Enter the fields manually or scan when connected.');scanBusy=true;render();message('Scanning receipt… Your photo is saved.');try{const result=await parseReceiptImage(images.get(r.receiptId).imageFull,setting('apiKey'),state.project.currency);Object.assign(r,result,{verified:false});await save();message('Scan complete. Check every field against the photo, then confirm the expense.');}finally{scanBusy=false;render();}}
function download(name,blob){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportPDF(){
  if(!state.project.projectTitle.trim()||!state.project.clientName.trim()||!state.contractor.name.trim()||!state.project.invoiceNumber.trim())throw new Error('Add project, client, contractor name, and invoice number before exporting.');
  if(!validDate(state.project.invoiceDate))throw new Error('Add a valid invoice date.');
  if(state.project.shootStart>state.project.shootEnd)throw new Error('Shoot end must be on or after shoot start.');
  if(state.expenses.some(r=>!r.verified))throw new Error('Review and confirm all receipts, or remove them, before exporting.');
  state.expenses.forEach(r=>validateReceipt(r,state.project.currency));
  if(!state.labor.length&&!state.expenses.length)throw new Error('Add at least one work item or expense.');
  if(state.labor.some(r=>!r.description.trim()))throw new Error('Give every work item a description.');
  if(!window.html2pdf)throw new Error('The PDF library did not load. Reload the app and retry.');
  renderBusy=true;const button=document.querySelector('[data-action=export]');button.disabled=true;$('#export-status').textContent='Preparing Korean text and receipt proofs…';
  let root;
  try{await save();await document.fonts.load('12px WrapKorean','영수증 청구서');await document.fonts.ready;
    root=document.createElement('div');root.className='invoice-paper exporting';root.style.setProperty('--invoice-accent',state.invoice.accent);root.innerHTML=renderInvoice(template(),enrichedState());document.body.append(root);await Promise.all([...root.querySelectorAll('img')].map(img=>img.decode()));
    const filename=(state.project.invoiceNumber||'WrapSheet').replace(/[^\p{L}\p{N}_-]/gu,'_')+'.pdf';
    await window.html2pdf().set({margin:10,filename,image:{type:'jpeg',quality:.96},html2canvas:{scale:2,useCORS:false,backgroundColor:'#ffffff',scrollY:0},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],avoid:['tr','figure','.invoice-totals']}}).from(root).save();
    await db.put('snapshots',{id:uid(),projectId:state.id,createdAt:Date.now(),state:structuredClone(state),template:structuredClone(template())});$('#export-status').textContent='PDF exported. Invoice snapshot saved on this device.';
  }finally{root?.remove();renderBusy=false;button.disabled=false;}
}
const actions={
  'retry-save':()=>save().then(()=>message('Project saved.')),
  'add-labor':async()=>{const kind=$('#labor-kind').value;state.labor.push({id:uid(),type:kind,description:kind,date:state.project.shootStart||today(),quantity:1,rate:0,unit:kind==='Overtime'?'hour':kind==='Mileage'?'km':kind.includes('Rental')?'item':'day',taxable:true});await save();render();},
  'remove-labor':async id=>{state.labor=state.labor.filter(r=>r.id!==id);await save();render();},
  'manual-receipt':async()=>{state.expenses.push({id:uid(),receiptId:null,vendor:'',date:today(),total:'',vat:0,currency:state.project.currency,category:'',verified:false,warning:''});await save();render();},
  'confirm-receipt':async id=>{const r=state.expenses.find(r=>r.id===id);validateReceipt(r,state.project.currency);r.verified=true;r.warning='';await save();message('Expense verified and included in the total.');render();},
  'remove-receipt':async id=>{const r=state.expenses.find(r=>r.id===id);state.expenses=state.expenses.filter(r=>r.id!==id);await save();if(r.receiptId){await db.remove('receipts',r.receiptId);images.delete(r.receiptId);}render();},
  'scan':scan,
  'remove-logo':async()=>{state.contractor.logo='';await save();render();},
  'export':exportPDF,
  'backup':async()=>{await save();download(`WrapSheet-${state.id}.json`,new Blob([JSON.stringify({schemaVersion:1,project:state,receipts:[...images.values()],templates:templates.filter(t=>t.id===state.invoice.templateId)},null,2)],{type:'application/json'}));message('Project backup downloaded. It includes receipt photos and excludes your API key.');}
};
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{if(b.dataset.go||b.dataset.tab){await go(b.dataset.go||b.dataset.tab);return;}if(b.dataset.action){if(scanBusy||renderBusy)return;b.disabled=true;try{await actions[b.dataset.action]?.(b.dataset.id);}finally{if(b.isConnected)b.disabled=false;}}}catch(error){fail(error);}});
// Persist as the user types as well as on blur (mobile and embedded browsers differ).
document.addEventListener('input',event=>{
  const el=event.target;if(!el.dataset.field||el.type==='checkbox'||el.tagName==='SELECT')return;
  if(el.type==='number'&&!validNumber(el.value,el.dataset.field==='project.taxRate'?100:el.dataset.field.endsWith('.quantity')?1e6:1e12))return;
  try{updateField(el.dataset.field,el.value,el);if(tab==='invoice')preview();}catch(error){fail(error);}
});
document.addEventListener('change',async event=>{const el=event.target;try{
  if(el.dataset.field){const path=el.dataset.field;try{updateField(path,el.type==='checkbox'?el.checked:el.value,el);}catch(error){if(el.type==='checkbox')el.checked=getPath(path);else el.value=getPath(path);throw error;}if(path==='project.currency'){message('Currency changed without converting amounts. Review all work rates and receipt currencies.');}if(tab==='invoice')preview();return;}
  if(['camera-input','receipt-input','logo-input','template-input'].includes(el.id)){
    if(scanBusy||renderBusy)throw new Error('Wait for the current operation to finish.');renderBusy=true;
    try{const files=[...el.files];if(el.id==='camera-input'||el.id==='receipt-input'){for(const file of files)await addPhoto(file);message(`${files.length} photo(s) saved. Scan or fill in the details, then confirm.`);}
    if(el.id==='logo-input'&&files[0]){state.contractor.logo=await compressImage(files[0],500,.9);await save();}
    if(el.id==='template-input'&&files[0]){if(files[0].size>200000)throw new Error('Template exceeds 200 KB. Upload a small HTML template without embedded assets.');const html=checkTemplate(sanitizeTemplate(await files[0].text()));const t={id:uid(),name:files[0].name.replace(/\.html?$/i,''),html};await db.put('templates',t);templates.push(t);state.invoice.templateId=t.id;await save();message('Template added. Safe structure and placeholders retained; styling follows your invoice settings.');}
    }finally{renderBusy=false;el.value='';render();}
  }
}catch(error){fail(error);}});
document.addEventListener('focusout',event=>{const el=event.target.closest('[data-edit]');if(!el)return;const path=el.dataset.edit;try{const value=el.textContent.trim();if(String(getPath(path))===value)return;updateField(path,value,el);if(path.startsWith('expenses.'))message('Expense edited. Reconfirm it in Receipts before export.');preview();}catch(error){el.textContent=getPath(path);fail(error);}});
document.addEventListener('keydown',event=>{if(event.target.matches('[data-edit]')&&event.key==='Enter'&&!event.shiftKey){event.preventDefault();event.target.blur();}});
$('#project-picker').addEventListener('change',async event=>{const id=event.target.value;try{if(scanBusy||renderBusy)throw new Error('Wait for the current operation before switching projects.');await saveChain;await loadProject(id);message('');}catch(error){event.target.value=state.id;fail(error);}});
$('#new-project').addEventListener('click',async()=>{try{if(scanBusy||renderBusy)return;await saveChain;state=newProject();images=new Map();tab='project';location.hash='project';message('');await save();setSetting('currentProjectId',state.id);render();}catch(error){fail(error);}});
$('#settings-button').addEventListener('click',()=>{$('#api-key').value=setting('apiKey');$('#settings').showModal();});
$('#close-settings').addEventListener('click',()=>$('#settings').close());
$('#settings-form').addEventListener('submit',event=>{event.preventDefault();setSetting('apiKey',$('#api-key').value.trim());$('#api-key').value='';$('#settings').close();message('Settings saved on this device.');});
$('#clear-key').addEventListener('click',()=>{setSetting('apiKey','');$('#api-key').value='';message('API key removed.');});
function network(){ $('#network').textContent=navigator.onLine?'● Online':'○ Offline'; }
window.addEventListener('online',network);window.addEventListener('offline',network);
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['project','work','receipts','invoice'].includes(next)&&!scanBusy&&!renderBusy){tab=next;render();}});
window.addEventListener('beforeunload',event=>{if($('#save-status').textContent!=='✓ Saved on this device'||scanBusy||renderBusy){event.preventDefault();event.returnValue='';}});
async function boot(){try{await db.openDB();projects=await db.all('projects');templates=await db.all('templates');const current=setting('currentProjectId');const existing=projects.find(p=>p.id===current)||projects.sort((a,b)=>b.updatedAt-a.updatedAt)[0];if(existing)await loadProject(existing.id);else{state=newProject();await save();setSetting('currentProjectId',state.id);}tab=['project','work','receipts','invoice'].includes(location.hash.slice(1))?location.hash.slice(1):'project';render();$('#save-status').textContent='✓ Saved on this device';network();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>message('Offline shell could not be installed. Keep a connection and reload to retry.'));}catch(error){$('#view').innerHTML='<div class="panel"><h2>Local storage is unavailable.</h2><p>Allow browser storage, leave private browsing if needed, and reload. Existing data has not been reset.</p><button onclick="location.reload()">Reload</button></div>';fail(error);}}
boot();
// Optional browser agent interface; the same visible state remains authoritative.
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_wrap_summary',description:'Read the active project totals and number of receipts awaiting verification. No API key is returned.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{if(!state)throw new Error('Workspace is loading.');return {project:state.project.projectTitle,currency:state.project.currency,...totals(state),pendingReceipts:state.expenses.filter(r=>!r.verified).length};}});
  register({name:'navigate_wrap_step',description:'Open a WrapSheet step without changing invoice data.',inputSchema:{type:'object',properties:{step:{type:'string',enum:['project','work','receipts','invoice']}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!['project','work','receipts','invoice'].includes(input.step))throw new Error('Choose project, work, receipts, or invoice.');await go(input.step);return {step:tab};}});
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
