import {money,totals,round} from './model.js';
export const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const presets=[{id:'production',name:'Production'},{id:'minimal',name:'Minimal'},{id:'traditional',name:'Traditional'},{id:'receipt-heavy',name:'Receipt-heavy'}];
const ko={invoiceTitle:'청구서',laborTitle:'작업 및 장비',expensesTitle:'실비 정산',totalTitle:'총 청구 금액',paymentTitle:'입금 안내',receiptsTitle:'영수증 증빙'};
// Conservative template vocabulary. No CSS, scripts, remote URLs, or active content survives.
export function sanitizeTemplate(source){
  const doc=new DOMParser().parseFromString(source,'text/html');
  const allowed=new Set(['SECTION','DIV','HEADER','FOOTER','MAIN','ARTICLE','H1','H2','H3','H4','P','SPAN','STRONG','B','EM','I','BR','HR','TABLE','THEAD','TBODY','TR','TH','TD','UL','OL','LI']);
  const blocked=new Set(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED','LINK','META','SVG','MATH','FORM','INPUT','BUTTON','TEXTAREA','SELECT','TEMPLATE','IMG','AUDIO','VIDEO']);
  const clean=node=>{for(const child of [...node.children]){if(blocked.has(child.tagName)){child.remove();continue;}clean(child);if(!allowed.has(child.tagName)){child.replaceWith(...child.childNodes);continue;}for(const a of [...child.attributes])child.removeAttribute(a.name);}};
  clean(doc.body);return doc.body.innerHTML;
}
export const placeholders=['invoiceTitle','contractorName','clientName','clientAddress','projectTitle','invoiceNumber','invoiceDate','dueDate','shootDates','contractorDetails','logo','laborTable','expenseTable','laborTotal','expenseTotal','taxTotal','totalAmountDue','totals','paymentDetails','notes','receiptGallery','footer'];
export function checkTemplate(html){const unknown=[...html.matchAll(/{{\s*(\w+)\s*}}/g)].map(m=>m[1]).filter(p=>!placeholders.includes(p));if(unknown.length)throw new Error(`Unknown placeholders: ${[...new Set(unknown)].join(', ')}`);for(const required of ['laborTable','expenseTable','totals'])if(!html.includes(`{{${required}}}`))throw new Error(`Template must contain {{${required}}} to keep invoice amounts reviewable.`);return html;}
export function renderInvoice(template,s,{editable=false}={}){
  const e=escapeHTML,c=s.project.currency,t=totals(s),o=s.invoice.options;
  const edit=(path,value,type='text')=>editable?`<span contenteditable="plaintext-only" role="textbox" aria-label="${e(path)}" data-edit="${e(path)}" data-type="${type}">${e(value)}</span>`:e(value);
  const label=k=>edit(`invoice.labels.${k}`,s.invoice.labels[k])+(o.bilingualLabels?` / ${ko[k]}`:'');
  const text=(path,value)=>edit(path,value);
  const cash=value=>e(money(value,c));
  const laborTable=`<section><h2>${label('laborTitle')}</h2><table><thead><tr><th>Description / Date</th><th>Qty / Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${s.labor.map((r,i)=>`<tr><td>${text(`labor.${i}.description`,r.description)}<br>${text(`labor.${i}.date`,r.date)}</td><td>${edit(`labor.${i}.quantity`,r.quantity,'number')} ${text(`labor.${i}.unit`,r.unit)}</td><td>${editable?edit(`labor.${i}.rate`,r.rate,'number'):cash(r.rate)}</td><td>${cash(round(r.quantity*r.rate,c))}${r.taxable?' *':''}</td></tr>`).join('')||'<tr><td colspan="4">No work items</td></tr>'}</tbody></table><p>* Taxable work. Currency: ${c}</p></section>`;
  const expenseTable=`<section><h2>${label('expensesTitle')}</h2><table><thead><tr><th>Vendor / Date</th>${o.showExpenseCategories?'<th>Category</th>':''}${o.showVat?'<th>Included VAT</th>':''}<th>Total paid</th></tr></thead><tbody>${s.expenses.map((r,i)=>r.verified?`<tr><td>${text(`expenses.${i}.vendor`,r.vendor)}<br>${text(`expenses.${i}.date`,r.date)}</td>${o.showExpenseCategories?`<td>${text(`expenses.${i}.category`,r.category)}</td>`:''}${o.showVat?`<td>${editable?edit(`expenses.${i}.vat`,r.vat,'number'):cash(r.vat)}</td>`:''}<td>${editable?edit(`expenses.${i}.total`,r.total,'number'):cash(r.total)}</td></tr>`:'').join('')||`<tr><td colspan="${2+Number(o.showVat)+Number(o.showExpenseCategories)}">No verified expenses</td></tr>`}</tbody></table><p>Reimbursements include receipt VAT; it is not added again.</p></section>`;
  const receiptGallery=o.showReceiptGallery?`<section><h2>${label('receiptsTitle')}</h2><div class="proof-grid">${s.expenses.filter(r=>r.verified).map((r,i)=>`<figure>${r.imageThumbnail?`<img src="${e(r.imageThumbnail)}" alt="Receipt ${i+1}">`:'<p>Manual expense — no photo attached</p>'}<figcaption>${String(i+1).padStart(2,'0')} / ${e(r.vendor)} · ${e(r.date)} · ${cash(r.total)}<br>${e(r.category)}</figcaption></figure>`).join('')||'<p>No receipt proofs attached.</p>'}</div></section>`:'';
  const totalBlock=`<div class="invoice-totals"><div><span>Work subtotal</span><b>${cash(t.labor)}</b></div><div><span>Labor tax (${e(s.project.taxRate)}%)</span><b>${cash(t.tax)}</b></div><div><span>Expenses</span><b>${cash(t.expenses)}</b></div><div class="amount-due"><span>${label('totalTitle')}</span><b>${cash(t.total)}</b></div></div>`;
  const paymentDetails=o.showBankInfo?`<section><h2>${label('paymentTitle')}</h2><p>${text('contractor.bankName',s.contractor.bankName)}<br>${text('contractor.accountNumber',s.contractor.accountNumber)}<br>${text('contractor.paymentTerms',s.contractor.paymentTerms)}</p></section>`:'';
  const notes=o.showNotes?`<section><h2>Notes</h2><p>${text('project.notes',s.project.notes)}</p></section>`:'';
  const values={invoiceTitle:label('invoiceTitle'),contractorName:text('contractor.name',s.contractor.name),clientName:text('project.clientName',s.project.clientName),clientAddress:text('project.clientAddress',s.project.clientAddress),projectTitle:text('project.projectTitle',s.project.projectTitle),invoiceNumber:text('project.invoiceNumber',s.project.invoiceNumber),invoiceDate:text('project.invoiceDate',s.project.invoiceDate),dueDate:text('project.dueDate',s.project.dueDate),shootDates:`${e(s.project.shootStart)} – ${e(s.project.shootEnd)}`,contractorDetails:`${text('contractor.address',s.contractor.address)}<br>${text('contractor.email',s.contractor.email)} · ${text('contractor.phone',s.contractor.phone)}<br>${text('contractor.taxId',s.contractor.taxId)}`,logo:s.contractor.logo?`<img class="logo" src="${e(s.contractor.logo)}" alt="Contractor logo">`:'',laborTable,expenseTable,receiptGallery,laborTotal:cash(t.labor),expenseTotal:cash(t.expenses),taxTotal:cash(t.tax),totalAmountDue:cash(t.total),totals:totalBlock,paymentDetails,notes,footer:text('contractor.footer',s.contractor.footer)};
  if(template?.html){const safe=checkTemplate(sanitizeTemplate(template.html));return safe.replace(/{{\s*(\w+)\s*}}/g,(_,key)=>values[key]??'');}
  return `<article class="${presets.some(p=>p.id===template?.id)?template.id:'production'}"><header class="invoice-header"><div>${values.logo}<h1>${values.invoiceTitle}</h1><p>${values.contractorName}<br>${values.contractorDetails}</p></div><div><b>${values.invoiceNumber}</b><p>Issued ${values.invoiceDate}<br>Due ${values.dueDate}</p></div></header><h2>${values.projectTitle}</h2><p>Bill to: ${values.clientName}<br>${values.clientAddress}<br>Shoot: ${values.shootDates}</p>${laborTable}${expenseTable}${totalBlock}${paymentDetails}${notes}${receiptGallery}<p class="invoice-footer">${values.footer}</p></article>`;
}
